name: 同步完整版 IPTV 源（无交互／实时日志＋提取 M3U）

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 签出当前仓库（含完整历史）
      - name: Checkout this repository (完整历史)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # 2. 签出上游的 YanG-1989/m3u 脚本仓库到 m3u-repo
      - name: Checkout YanG-1989/m3u repository
        uses: actions/checkout@v4
        with:
          repository: YanG-1989/m3u
          path: m3u-repo
          fetch-depth: 1

      # 3. 用 sed 注释掉脚本里所有交互提示，强制选择 1
      - name: Patch NoobIPTV.sh to skip interactive prompts
        working-directory: m3u-repo
        run: |
          cp NoobIPTV.sh NoobIPTV.sh.bak
          # 用 sed 把所有 read -p 替成 choice=1
          sed -i 's/^ *read -p.*$/choice=1/' NoobIPTV.sh

          # 删除脚本中打印菜单或其他提示的行，避免日志刷屏
          sed -i '/请选择一个项目/d; /Pixman 菜单/d; /Fourgtv 项目/d; /Doubebly 项目/d; /Tool/d' NoobIPTV.sh

          chmod +x NoobIPTV.sh

      # 4. 运行 patched NoobIPTV.sh，实时打印日志，并提取 M3U
      - name: Run patched NoobIPTV.sh with real-time logs and extract M3U
        working-directory: m3u-repo
        run: |
          # 先给脚本可执行权限（若上一步没做）
          chmod +x NoobIPTV.sh

          # 1) 把所有输出都 tee 到 output.log，同时打印在控制台
          ./NoobIPTV.sh 2>&1 | tee output.log

          # 2) 从 output.log 中提取出从 #EXTM3U 开始的 M3U 内容到 Gather.m3u
          grep -A 999 '^#EXTM3U' output.log > Gather.m3u

          # 3) 列出 m3u-repo 目录下的文件，确认 Gather.m3u 存在
          echo "=== m3u-repo 目录下文件 ==="
          ls -1 .

      # 5. 拷贝生成的 M3U 到主仓库，并生成 TXT（可选）
      - name: Copy and optionally generate TXT
        run: |
          cp m3u-repo/Gather.m3u ./FullGather.m3u
          grep -Eo "http[s]?://.*" FullGather.m3u > FullGather.txt || true
          echo "=== 根目录下文件 ==="
          ls -1 .

      # 6. 部署到 gh-pages 分支
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
          keep_files: true
